name = "freewhen"
pages_build_output_dir = "dist"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "freewhen"
database_id = "00000000-0000-0000-0000-000000000000"
